#pragma once

#include "latent/imaging/RawFrame.h"
#include <array>
#include <cstddef>
#include <cstdint>
#include <memory>
#include <span>
#include <string>

namespace latent::reference {
// The normalized tile is the sole CPU/GPU CFA boundary. Channel IDs are
// generated by samplingChannelAt; no backend may reinterpret a CFA enum.
struct MosaicEvidence {
    float value = 0, variance = 0;
    std::uint32_t channel = 0, valid = 0;
};
struct ReconstructionWarp {
    float x = 0, y = 0, confidence = 0, reserved = 0;
    // Inverse local geometric Jacobian, row-major. Sample offsets are fitted in
    // reference photosite coordinates, not in each source frame's coordinates.
    std::array<float,4> sourceToReference{1,0,0,1};
};
inline constexpr std::size_t kReconstructionBasis = 6;
inline constexpr std::size_t kReconstructionMoments = 21;
struct ReconstructionAnchor {
    std::array<float,4> mean{}, noise{}, spatial{};
    // inverse kernel covariance xx,xy,yy; fourth lane reserved
    std::array<float,4> precision{1,0,1,0};
    std::array<float,4> referenceWarp{}; // xy phase origin; remaining lanes reserved
};
struct ReconstructionAccumulator {
    // Lower-triangular symmetric matrices, row-major: index i*(i+1)/2+j.
    // The zeroth moments ARE the legacy Gaussian estimate; no duplicate sums.
    std::array<std::array<float,4>,kReconstructionBasis> signal{};
    std::array<std::array<float,4>,kReconstructionMoments> gram{}, noiseGram{}, noiseBoundGram{}, frameRoot{};
    std::array<std::array<float,4>,kReconstructionBasis> referenceMoments{};
    // frameRoot packs an upper-triangular QR factor (R[row,column] at
    // column*(column+1)/2+row), avoiding cancellation in signed frame leverage.
    // Weighted circular moments at x, y, x+y, x-y (one cycle/photosite).
    std::array<std::array<float,4>,4> phaseCos{}, phaseSin{};
    // RGB support; fourth lane reserved.
    std::array<float,4> nearWeight{};
};
// Sensor-reference normalized, green-balanced camera RGB, NOT an AP1 SceneFrame.
// If reference COLOR_CORRECTION_GAINS is provided, G0/G1 are multiplied by
// gainG0/meanGainG and gainG1/meanGainG before their merge. R/B are unchanged.
// Downstream RGB white balance is [gainR,meanGainG,gainB], applied exactly once. Invalid
// channels have confidence zero. Consumers must retain this mask, not pretend
// that zero-filled missing samples are measured black.
struct ReconstructedPixel {
    std::array<float,4> rgb{}, variance{}, effectiveFrames{}, confidence{};
    // Observed phase diversity is a conservative geometric diagnostic, NOT a
    // calibrated resolution/quality probability. modelBlend is the actual fit
    // contribution after conditioning, SNR, phase and support gates.
    std::array<float,4> samplingDiversity{}, modelBlend{};
};
static_assert(sizeof(MosaicEvidence)==16 && sizeof(ReconstructionWarp)==32);
static_assert(sizeof(ReconstructionAnchor)==80 && sizeof(ReconstructionAccumulator)==1680 && sizeof(ReconstructedPixel)==96);
struct DirectKernelPolicy {
    float detailSigma = 0.7F;
    float residualCutoff = 4.0F;
    float aliasAllowance = 0.15F;
    // Dimensionless noise regularizer relative to local evidence amplitude^2.
    // Unlike an absolute sensor-unit floor, this preserves intensity scaling.
    float relativeVarianceFloor = 1.0e-8F;
    float minimumConfidence = 0.15F;
    // Explicit delegated estimator policy; zero gives the Gaussian ablation.
    float quadraticStrength = 1.0F;
    float fitRegularization = 1.0e-3F;
    // Bound normalized prediction leverage; taper ill-supported extrapolation
    // before trusting a polynomial at cropped borders or sparse color support.
    float maximumFitLeverage = 16.0F;
    // Opt-in high-detail policy for well-registered, phase-diverse bursts.
    // Output-grid scale remains an independent, explicit runtime request.
    [[nodiscard]] static DirectKernelPolicy superResolution() {
        DirectKernelPolicy p;p.detailSigma=0.5F;p.aliasAllowance=1.0F;return p;
    }
};
struct DirectKernelGeometry {
    imaging::SensorRect sourceTile{};
    std::uint32_t radiusX = 2, radiusY = 2;
    float fallbackSigma = 1.0F;
    bool referenceFrame = false;
    // Remosaicing destroys the independent-pixel noise assumption. Use a
    // same-frame fully-correlated variance bound instead of false precision.
    bool correlatedSpatialNoise = false;
};
void validateDirectKernelPolicy(const DirectKernelPolicy&);
void validateDirectKernelInput(std::span<const MosaicEvidence>, std::span<const ReconstructionWarp>,
    const DirectKernelGeometry&);
void makeReconstructionAnchors(std::span<const MosaicEvidence>, std::span<const ReconstructionWarp>,
    const DirectKernelGeometry&, const DirectKernelPolicy&, std::span<ReconstructionAnchor>);
void accumulateDirectReconstruction(std::span<const MosaicEvidence>, std::span<const ReconstructionWarp>,
    std::span<const ReconstructionAnchor>, const DirectKernelGeometry&, const DirectKernelPolicy&,
    std::span<ReconstructionAccumulator>);
void finishDirectReconstruction(std::span<const ReconstructionAnchor>, std::span<const ReconstructionAccumulator>,
    std::span<ReconstructedPixel>, const DirectKernelPolicy& = {});

// One arena per execution, reused for every output tile. The reference
// implementation is allocation-free inside the kernels. Backends keep all
// accumulation on device until a tile is finalized; no per-frame readback.
class DirectTileExecutor {
public:
    virtual ~DirectTileExecutor() = default;
    // Initializes the anchor AND includes the reference contribution exactly once.
    virtual void begin(std::span<const MosaicEvidence>, std::span<const ReconstructionWarp>,
        const DirectKernelGeometry&) = 0;
    virtual void add(std::span<const MosaicEvidence>, std::span<const ReconstructionWarp>,
        const DirectKernelGeometry&) = 0;
    virtual void finish(std::span<ReconstructedPixel>) = 0;
    // Optional coherent arenas. Valid until executor destruction; synchronous
    // begin/add/finish return only after device completion. Caller must not
    // access these spans during dispatch or retain output beyond the next tile.
    // Empty spans request caller-owned storage (reference backend).
    virtual std::span<MosaicEvidence> inputArena() { return {}; }
    virtual std::span<ReconstructionWarp> warpArena() { return {}; }
    virtual std::span<ReconstructedPixel> outputArena() { return {}; }
    [[nodiscard]] virtual std::uint64_t deviceBytes() const = 0;
    [[nodiscard]] virtual std::uint64_t transferBytes() const = 0;
    [[nodiscard]] virtual double gpuMilliseconds() const = 0;
};
[[nodiscard]] std::unique_ptr<DirectTileExecutor> makeReferenceDirectExecutor(std::size_t maxPixels,
    const DirectKernelPolicy&);
}  // namespace latent::reference
