#pragma once

#include "latent/imaging/RawFrame.h"
#include <array>
#include <cstdint>
#include <memory>
#include <span>
#include <string>

namespace latent::reference {
// The normalized tile is the sole CPU/GPU CFA boundary. Channel IDs are
// generated by samplingChannelAt; no backend may reinterpret a CFA enum.
struct MosaicEvidence {
    float value = 0, variance = 0;
    std::uint32_t channel = 0, valid = 0;
};
struct ReconstructionWarp { float x = 0, y = 0, confidence = 0, reserved = 0; };
struct ReconstructionAnchor {
    std::array<float,4> mean{}, noise{}, spatial{};
    // inverse kernel covariance xx,xy,yy; fourth lane reserved
    std::array<float,4> precision{1,0,1,0};
};
struct ReconstructionAccumulator {
    std::array<float,4> value{}, weight{}, variance{}, frameWeightSquared{};
    std::array<float,4> nearWeight{}, referenceWeight{};
};
// Sensor-reference normalized, green-balanced camera RGB, NOT an AP1 SceneFrame.
// If reference COLOR_CORRECTION_GAINS is provided, G0/G1 are multiplied by
// gainG0/meanGainG and gainG1/meanGainG before their merge. R/B are unchanged.
// Downstream RGB white balance is [gainR,meanGainG,gainB], applied exactly once. Invalid
// channels have confidence zero. Consumers must retain this mask, not pretend
// that zero-filled missing samples are measured black.
struct ReconstructedPixel {
    std::array<float,4> rgb{}, variance{}, effectiveFrames{}, confidence{};
};
static_assert(sizeof(MosaicEvidence)==16 && sizeof(ReconstructionWarp)==16);
static_assert(sizeof(ReconstructionAnchor)==64 && sizeof(ReconstructionAccumulator)==96 && sizeof(ReconstructedPixel)==64);
struct DirectKernelPolicy {
    float detailSigma = 0.7F;
    float residualCutoff = 4.0F;
    float aliasAllowance = 0.15F;
    float varianceFloor = 1.0e-8F;
    float minimumConfidence = 0.15F;
};
struct DirectKernelGeometry {
    imaging::SensorRect sourceTile{};
    std::uint32_t radiusX = 2, radiusY = 2;
    float fallbackSigma = 1.0F;
    bool referenceFrame = false;
    // Remosaicing destroys the independent-pixel noise assumption. Use a
    // same-frame fully-correlated variance bound instead of false precision.
    bool correlatedSpatialNoise = false;
};
void validateDirectKernelPolicy(const DirectKernelPolicy&);
void validateDirectKernelInput(std::span<const MosaicEvidence>, std::span<const ReconstructionWarp>,
    const DirectKernelGeometry&);
void makeReconstructionAnchors(std::span<const MosaicEvidence>, std::span<const ReconstructionWarp>,
    const DirectKernelGeometry&, const DirectKernelPolicy&, std::span<ReconstructionAnchor>);
void accumulateDirectReconstruction(std::span<const MosaicEvidence>, std::span<const ReconstructionWarp>,
    std::span<const ReconstructionAnchor>, const DirectKernelGeometry&, const DirectKernelPolicy&,
    std::span<ReconstructionAccumulator>);
void finishDirectReconstruction(std::span<const ReconstructionAnchor>, std::span<const ReconstructionAccumulator>,
    std::span<ReconstructedPixel>);

// One arena per execution, reused for every output tile. The reference
// implementation is allocation-free inside the kernels. Backends keep all
// accumulation on device until a tile is finalized; no per-frame readback.
class DirectTileExecutor {
public:
    virtual ~DirectTileExecutor() = default;
    // Initializes the anchor AND includes the reference contribution exactly once.
    virtual void begin(std::span<const MosaicEvidence>, std::span<const ReconstructionWarp>,
        const DirectKernelGeometry&) = 0;
    virtual void add(std::span<const MosaicEvidence>, std::span<const ReconstructionWarp>,
        const DirectKernelGeometry&) = 0;
    virtual void finish(std::span<ReconstructedPixel>) = 0;
    // Optional coherent arenas. Valid until executor destruction; synchronous
    // begin/add/finish return only after device completion. Caller must not
    // access these spans during dispatch or retain output beyond the next tile.
    // Empty spans request caller-owned storage (reference backend).
    virtual std::span<MosaicEvidence> inputArena() { return {}; }
    virtual std::span<ReconstructionWarp> warpArena() { return {}; }
    virtual std::span<ReconstructedPixel> outputArena() { return {}; }
    [[nodiscard]] virtual std::uint64_t deviceBytes() const = 0;
    [[nodiscard]] virtual std::uint64_t transferBytes() const = 0;
    [[nodiscard]] virtual double gpuMilliseconds() const = 0;
};
[[nodiscard]] std::unique_ptr<DirectTileExecutor> makeReferenceDirectExecutor(std::size_t maxPixels,
    const DirectKernelPolicy&);
}  // namespace latent::reference
